### ISSUE TITLE
README.md neads to be changed to match packer/build.json

### ISSUE THREAD

**Issue by calciu** [mcapuccini/SparkNow#1]
In README.md 
"export PACKER_FLAVOUR ...    " needs to be replaced with 
"export PACKER_FLAVOR ...    "  (that is FLAVOR not FLAVOUR)
in order to match packer/build.json
"flavor": "{{env `PACKER_FLAVOR`}}",

**Comment by mcapuccini** [comment]
@calciu if you feel like, you could send me a pull request for this. Otherwise, I'll fix it asap.

**Comment by calciu** [comment]
its ok for me the way you did it. You replaced in packer/build.json FLAVOR with FLAVOUR.

**Comment by mcapuccini** [comment]
I'll fix the typo at a certain point :slightly_smiling_face:
